In [5]:
import pandas as pd


data = {
    'Name': ['A', 'B', 'C', 'D', 'E'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [50000, 60000, 55000, 70000, 52000],
    'Experience': [2, 5, 3, 8, 4]
}
df = pd.DataFrame(data)
df

  Name  Gender Department  Salary  Experience
0    A  Female         IT   50000           2
1    B    Male         HR   60000           5
2    C  Female         IT   55000           3
3    D    Male    Finance   70000           8
4    E  Female         HR   52000           4

In [6]:
df.describe()

             Salary  Experience
count      5.000000    5.000000
mean   57400.000000    4.400000
std     7987.490219    2.302173
min    50000.000000    2.000000
25%    52000.000000    3.000000
50%    55000.000000    4.000000
75%    60000.000000    5.000000
max    70000.000000    8.000000

In [9]:
df[df["Gender"]=="Female"]["Salary"].mean()

np.float64(52333.333333333336)

In [8]:
df[df["Salary"]>5000].describe()

             Salary  Experience
count      5.000000    5.000000
mean   57400.000000    4.400000
std     7987.490219    2.302173
min    50000.000000    2.000000
25%    52000.000000    3.000000
50%    55000.000000    4.000000
75%    60000.000000    5.000000
max    70000.000000    8.000000

In [45]:
df["Salary"].mean()

np.float64(57400.0)

In [46]:
df["Salary"].median()

55000.0

In [50]:
mode_val = df["Salary"].mode()
print("Mode:", mode_val)

Mode: 0    50000
1    52000
2    55000
3    60000
4    70000
Name: Salary, dtype: int64

In [13]:
df.groupby('Department')['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
Department,,,,,,,,
Finance,1.0,70000.0,NaN,70000.0,70000.0,70000.0,70000.0,70000.0
HR,2.0,56000.0,5656.854249,52000.0,54000.0,56000.0,58000.0,60000.0
IT,2.0,52500.0,3535.533906,50000.0,51250.0,52500.0,53750.0,55000.0

In [15]:
df.groupby('Department')['Salary'].agg(['count','mean','min'])

            count     mean    min
Department
Finance         1  70000.0  70000
HR              2  56000.0  52000
IT              2  52500.0  50000

In [20]:
df['Salary_Category'] = df['Salary'].apply(
    lambda x: 'High' if x > 60000 else 'Medium' if x >= 50000 else 'Low'
)
df['Exp_cat']=df['Experience'].apply(
    lambda x: 'Sr' if x >= 8 else 'Jr' if x >= 3 else 'Fresher'
)
df

  Name  Gender Department  Salary  Experience Salary_Category  Exp_cat
0    A  Female         IT   50000           2          Medium  Fresher
1    B    Male         HR   60000           5          Medium       Jr
2    C  Female         IT   55000           3          Medium       Jr
3    D    Male    Finance   70000           8            High       Sr
4    E  Female         HR   52000           4          Medium       Jr

In [33]:
df['Promotion_Eligible'] = df.apply(
    lambda row: 'Yes' if (row['Salary'] > 50000) else 'No' , axis = 1
)
df

,Name,Gender,Department,Salary,Experience,Salary_Category,Exp_cat,Promotion_Eligible
0,A,Female,IT,50000,2,Medium,Fresher,No
1,B,Male,HR,60000,5,Medium,Jr,Yes
2,C,Female,IT,55000,3,Medium,Jr,Yes
3,D,Male,Finance,70000,8,High,Sr,Yes
4,E,Female,HR,52000,4,Medium,Jr,Yes

In [41]:
## Conditional bonus calculation
df["Bonus"] = df.apply(
    lambda row: row["Salary"]*0.10 if(row["Department"]=='IT')
    else row["Salary"] * 0.08 if(row["Department"] == 'HR')
    else row["Salary"] * 0.12 ,
axis = 1
)
df

,Name,Gender,Department,Salary,Experience,Salary_Category,Exp_cat,Promotion_Eligible,Bonus
0,A,Female,IT,50000,2,Medium,Fresher,No,5000.0
1,B,Male,HR,60000,5,Medium,Jr,Yes,4800.0
2,C,Female,IT,55000,3,Medium,Jr,Yes,5500.0
3,D,Male,Finance,70000,8,High,Sr,Yes,8400.0
4,E,Female,HR,52000,4,Medium,Jr,Yes,4160.0

In [ ]:
##