In [1]:
#Hierarchical Indexing means a DataFrame has more than one index level (multiple indexes for rows or columns).-

In [39]:
import pandas as pd

data = {
    "Region": ["North", "North", "North", "South", "South", "South"],
    "Department": ["IT", "HR", "Sales", "IT", "HR", "Sales"],
    "Year": [2023, 2023, 2023, 2023, 2023, 2023],
    "Sales": [100000, 50000, 75000, 90000, 45000, 70000]
}

df = pd.DataFrame(data)

#df = df.set_index(["Region", "Department", "Year"])
print(df)

  Region Department  Year   Sales
0  North         IT  2023  100000
1  North         HR  2023   50000
2  North      Sales  2023   75000
3  South         IT  2023   90000
4  South         HR  2023   45000
5  South      Sales  2023   70000

In [40]:
#sets Region and Department as hierarchical (multi-level) row indexes
df.set_index(["Region", "Department"], inplace=True)
df

                   Year   Sales
Region Department
North  IT          2023  100000
       HR          2023   50000
       Sales       2023   75000
South  IT          2023   90000
       HR          2023   45000
       Sales       2023   70000

In [42]:
#get north Region data with IT Department
df.loc[("North", "IT")]

Year       2023
Sales    100000
Name: (North, IT), dtype: int64

In [45]:
#Get North Region Data
df.loc["North"]

            Year   Sales
Department
IT          2023  100000
HR          2023   50000
Sales       2023   75000

In [58]:
tuples = [
    ("North", "IT"),
    ("North", "HR"),
    ("South", "IT"),
    ("South", "HR")
]
index = pd.MultiIndex.from_tuples(tuples, 
                                  names=["Region", "Department"])
df1= pd.DataFrame({"Sales": [100000, 50000, 90000, 45000]},index=index)
df1

                    Sales
Region Department
North  IT          100000
       HR           50000
South  IT           90000
       HR           45000

In [66]:
pop = [2020, 2021, 2022]
df2 = pd.DataFrame({'Year':pop})
df2

   Year
0  2020
1  2021
2  2022

In [70]:
#Methods of MultiIndex Creation
import numpy as np
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'b', 'c', 'd'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

        data1     data2
a 1  0.880143  0.049931
b 2  0.735863  0.121745
c 1  0.207172  0.651221
d 2  0.384071  0.055202

In [74]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64